<html>
<head>
    <title>Access is Denied.</title>
</head>
<body>
<div class="row">
    <div class="col-xs-12 text-center">
<#--        <img src="/static/img/AccessDeniedError.png">-->
        <h1 class="text-danger"><i class="fa fa-exclamation-circle"></i> Access Denied.</h1>
    </div>
</div>
</body>
</html>

<#--<h1>Access is denied.<button class="btn btn-link" onclick="history.back();"><i class="pli-arrow-back"></i> 돌아가기</button> </h1>-->